---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-postgres
  namespace: dz5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: my-postgres
    spec:
      initContainers:
      - image: busybox
        name: mount-permissions-fix
        command: ["sh", "-c", "chmod 777 /var/lib/postgresql/data"]
        volumeMounts:
        - name: pg-stor
          mountPath: "/var/lib/postgresql/data"
      containers:    
      - image: postgres:10.13
        name: postgres
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRES_USER
          value: "testuser"
        - name: POSTGRES_DB
          value: "testdatabase"
        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: my-secret
              key: pg_password
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        volumeMounts:
          - name: pg-stor
            mountPath: "/var/lib/postgresql/data"
      volumes:
        - name: pg-stor
          persistentVolumeClaim:
            claimName: pgdata
