apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-volume
  namespace: l5
  labels:
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgresql"