---
apiVersion: v1
data:
  KEY: UmRtUGFzczFAMw==
kind: Secret
metadata:
  creationTimestamp: "2023-05-12T14:19:20Z"
  name: rdm-secret
  namespace: default
  resourceVersion: "100538"
  selfLink: /api/v1/namespaces/default/secrets/rdm-secret
  uid: f07e890e-1f33-457c-bd8f-78c6ee46cc87
type: Opaque
