apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-02-02T15:17:11Z"
  generation: 1
  labels:
    app: kubedoom
  name: kubedoom
  namespace: kubedoom
  resourceVersion: "33011"
  uid: 710ba83a-ca8f-4961-8516-2bd37526d25d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kubedoom
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kubedoom
    spec:
      containers:
      - image: storaxdev/kubedoom:0.5.0
        imagePullPolicy: IfNotPresent
        name: kubedoom
        ports:
        - containerPort: 5900
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2023-02-02T15:16:11Z"
    lastUpdateTime: "2023-02-02T15:16:12Z"
    message: ReplicaSet "kubedoom-7d49598dd6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-02-02T15:37:36Z"
    lastUpdateTime: "2023-02-02T15:37:36Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
