---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dep
hostNetwork: true
serviceAccountName: kubedoom
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: storaxdev/kubedoom:0.5.0
        name: kd
        ports:
        - containerPort: 5900
          protocol: TCP
