---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-volume
  namespace: lesson7
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/prometheus"