---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "csi-ceph-ssd-gz1"