---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus-sts
spec:
  serviceName: prometheus-srv
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccount: prometheus
      initContainers:
      - image: busybox
        name: mount-permissions-fix
        command: ["sh", "-c", "chmod 777 /prometheus"]
        volumeMounts:
        - name: prometheus-disk
          mountPath: /prometheus
      containers:
        - name: prometheus-app
          image: prom/prometheus:v2.19.2
          ports:
            - name: admin
              protocol: TCP
              containerPort: 9090
          volumeMounts:
            - name: prometheus-cfg
              mountPath: /etc/prometheus
      volumes:
        - name: prometheus-cfg
          configMap:
            name: prometheus-cfg
        - name: prometheus-disk
          persistentVolumeClaim:
            claimName: prometheus-disk
  volumeClaimTemplates:
    - metadata:
        name: prometheus-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
        storageClassName: csi-ceph-hdd-gz1-retain