apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv-nfs
spec:
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.0
    - timeo=60
    - retrans=10
  capacity:
    storage: 10Gi
  nfs:
    server: 10.0.0.10
    path: "/shares/share-698c1591-5d1c-41b0-b08c-da96e6c493d9"
  persistentVolumeReclaimPolicy: "Recycle"
