---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-nfs-01
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "csi-ceph-hdd-gz1"
