kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pg-pvc-nfs-blk
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: pg-pv-nfs
  storageClassName: ""
