---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gb-4-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "csi-ceph-ssd-gz1"
