FROM python:3.10-alpine3.15
LABEL maintainer="Yakov Gashkov <y.gashkov@gmail.com>"
WORKDIR /app
COPY . /app
RUN pip3.10 install -r requirements.txt --upgrade
RUN chmod +x ./app.py
EXPOSE 8080
RUN ./app.py
